# Database configuration
# Only MariaDB is supported
db:
    # JDBC url
    jdbc: jdbc:mariadb://localhost:3306/your_db_name
    # Database user
    user: root
    # Database password
    password: ChangeThis!

    # Advanced configuration (do not touch unless you know what you are doing)
    # HikariCP. Comment out any data source property to disable setting it.
    cachePrepStmts: true
    prepStmtCacheSize: 250
    prepStmtCacheSqlLimit: 2048
    useServerPrepStmts: true
    useLocalSessionState: true
    rewriteBatchedStatements: true
    cacheResultSetMetadata: true
    cacheServerConfiguration: true
    elideSetAutoCommits: true
    maintainTimeStats: false

# Starting balance
# Set to `null` to disable automatically creating a personal account on first join
starting-balance: 0

# Server account
server-account:
    # If enabled, when the plugin is loaded an account will be created as player with UUID 00000000-0000-0000-0000-000000000000
    enabled: true
    # Display name for the server account
    name: Central Bank
    # Account type
    # Possible values:
    #   0: Personal account
    #   1: Business account
    type: 1
    # Starting balance
    # Use `Infinity` for infinite ∞ balance
    starting-balance: Infinity
