# Database configuration
# Only MariaDB is supported
db:
    # JDBC url
    jdbc: jdbc:mariadb://localhost:3306/your_db_name
    # Database user
    user: root
    # Database password
    password: ChangeThis!

    # Advanced configuration (do not touch unless you know what you are doing)
    # HikariCP. Comment out any data source property to disable setting it.
    cachePrepStmts: true
    prepStmtCacheSize: 250
    prepStmtCacheSqlLimit: 2048
    useServerPrepStmts: true
    useLocalSessionState: true
    rewriteBatchedStatements: true
    cacheResultSetMetadata: true
    cacheServerConfiguration: true
    elideSetAutoCommits: true
    maintainTimeStats: false

currency:
    # Currency symbol
    symbol: $

    # Currency format
    # See https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/text/DecimalFormat.html#special_pattern_character
    format: "#,##0.00"

# Starting balance
# Set to `null` to disable automatically creating a personal account on first join
starting-balance: 0

# Server account
server-account:
    # If enabled, when the plugin is loaded an account will be created as player with UUID 00000000-0000-0000-0000-000000000000
    enabled: true
    # Display name for the server account
    name: Central Bank
    # Account type
    # Possible values:
    #   0: Personal account
    #   1: Business account
    type: 1
    # Starting balance
    # Use `Infinity` for infinite ∞ balance
    starting-balance: Infinity

# Maximum number of accounts a player can have
# Account types:
#   0: Personal account
#   1: Business account
# Limits:
#   0: cannot have any accounts
#   -1: unlimited accounts
#
# Players can open accounts themselves if they have `bank.account.create`. These limits also apply if someone else
# creates bank accounts for other players with the admin permission `bank.account.create.other`. You can bypass the
# limits using `bank.account.create.bypass`.
account-limits:
    # Personal accounts
    0: 1
    # Business accounts
    1: -1

# Messages
messages:
    # Currency symbol
    currency: $

    # Errors
    errors:
        # You have no accounts
        no-accounts: "<red>(!) You have no bank accounts.</red>"
        # No permission
        no-permission: "<red>(!) You do not have permission to use this command.</red>"
        # Account not found
        account-not-found: "<red>(!) Account not found.</red>"
        # Command not recognised
        unknown-command: "<red>(!) Unknown command. Try <click:suggest_command:/bank help><gray>/bank help</gray></click>.</red>"
        # <type> the account type
        # <limit> the account limit for that type
        max-accounts: "<red>(!) You cannot open more than <limit> <type> accounts.</red>"

    # Account balance
    # Available placeholders:
    # <account> - Account name. Defaults to owner username or ID if not set.
    # <account-id> - Account ID
    # <account-type> - Account type (Personal or Business)
    # <balance> - Account balance without formatting, example: 123456.78
    # <balance-formatted> - Account balance with formatting, example: 123,456.78
    # <balance-short> - Account balance with formatting, example: 123k
    balance: |
        <green><account></green> <gray>(<account-type> account)</gray>
        <green>Balance:</green> <white><balance-formatted></white>
        <i><gray><click:copy_to_clipboard:<account-id>><hover:show_text:'Click to copy account ID'><account-id></hover></click></gray></i>

    # List accounts
    list-accounts:
        header: "<green>Bank accounts</green>"
        # Same placeholders as balance
        entry: "<dark_gray>*</dark_gray> <gray><click:run_command:/bank balance <account-id>><hover:show_text:'<white><account></white><newline><gray><account-type> - <green><balance-formatted></green></gray><newline><gray>Click to view'><account></hover></click> - <white><balance-short></white></gray>"

    # Plugin reload
    reload: "<green>(!) Plugin configuration reloaded</green>"

    # Account created (same placeholders as balance)
    account-created: "<green>(!) Successfully created <account-type> account: <account></green> <click:run_command:/bank balance <account-id>><gray>Click to view</gray></click>"
