# Database configuration
# Only MariaDB is supported
db:
    # JDBC url
    jdbc: jdbc:mariadb://localhost:3306/your_db_name
    # Database user
    user: root
    # Database password
    password: ChangeThis!

    # Advanced configuration (do not touch unless you know what you are doing)
    # HikariCP. Comment out any data source property to disable setting it.
    cachePrepStmts: true
    prepStmtCacheSize: 250
    prepStmtCacheSqlLimit: 2048
    useServerPrepStmts: true
    useLocalSessionState: true
    rewriteBatchedStatements: true
    cacheResultSetMetadata: true
    cacheServerConfiguration: true
    elideSetAutoCommits: true
    maintainTimeStats: false

currency:
    # Currency symbol
    symbol: $

    # Currency format
    # See https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/text/DecimalFormat.html#special_pattern_character
    format: "#,##0.00"

# Starting balance
# Set to `null` to disable automatically creating a personal account on first join
starting-balance: 0

# Server account
server-account:
    # If enabled, when the plugin is loaded an account will be created as player with UUID 00000000-0000-0000-0000-000000000000
    enabled: true
    # Display name for the server account
    name: Central Bank
    # Account type
    # Possible values:
    #   0: Personal account
    #   1: Business account
    type: 1
    # Starting balance
    # Use `Infinity` for infinite ∞ balance
    starting-balance: Infinity

# Maximum number of accounts a player can have
# Account types:
#   0: Personal account
#   1: Business account
# Limits:
#   0: cannot have any accounts
#   -1: unlimited accounts
#
# Players can open accounts themselves if they have `bank.account.create`. These limits also apply if someone else
# creates bank accounts for other players with the admin permission `bank.account.create.other`. You can bypass the
# limits using `bank.account.create.bypass`.
account-limits:
    # Personal accounts
    0: 1
    # Business accounts
    1: -1

# Transfer confirmation
transfer-confirmation:
    # If enabled, players will be shown a transfer overview asking them to confirm the transfer
    enabled: true
    # Minimum transfer amount to show confirmation for
    # Min transfer amount is > 0, so setting this to 0 will enable confirmation for all transfers amounts
    min-amount: 200
    # If true, confirmation will not be required for transfers between own accounts
    bypass-own-accounts: true

# Messages
messages:
    # Currency symbol
    currency: $

    # Errors
    errors:
        # You have no accounts
        no-accounts: "<red>(!) You have no bank accounts.</red>"
        # No permission
        no-permission: "<red>(!) You do not have permission to use this command.</red>"
        # Account not found
        account-not-found: "<red>(!) Account not found.</red>"
        # Command not recognised
        unknown-command: "<red>(!) Unknown command. Try <click:suggest_command:/bank help><gray>/bank help</gray></click>.</red>"
        # <type> the account type
        # <limit> the account limit for that type
        max-accounts: "<red>(!) You cannot open more than <limit> <type> accounts.</red>"
        rename-personal: "<red>(!) You cannot rename personal accounts.</red>"
        # You do not own this account
        not-account-owner: "<red>(!) You are not the owner of account <gray><account></gray></red>"
        # Account frozen (placeholders same as balance)
        frozen: "<gold>(!) <account-type> account <gray><account> (<account-id>)</gray> is frozen. This account cannot initiate or receive transactions.</gold>"
        # Cannot transfer to same account
        same-from-to: "<red>(!) The from and to accounts must be different.</red>"
        # You can only make transfer between your own accounts
        transfer-self-only: "<red>(!) You can only make transfers between your own accounts.</red>"
        # You can only transfer to account that are not yours
        transfer-other-only: "<red>(!) You cannot make a transfer between your own accounts.</red>"
        # Invalid number. Placeholder <number> is the invalid number
        invalid-number: "<red>(!) Invalid number: <gray><number></gray></red>"
        # $0 transfer
        zero-transfer: "<red>(!) The amount to transfer must be greater than zero.</red>"
        # Insufficient funds (placeholders same as balance)
        insufficient-funds: "<red>(!) Your account has insufficient funds. You have <gray><balance-formatted></gray></red>"
        # Trying to close an account that has non-zero balance
        closing-balance: "<red>(!) You cannot close an account that has a non-zero balance. This account has <gray><balance-formatted></gray></red>"

    # Account balance
    # Available placeholders:
    # <account> - Account name. Defaults to owner username or ID if not set.
    # <account-id> - Account ID
    # <account-type> - Account type (Personal or Business)
    # <account-owner> - Account owner username
    # <balance> - Account balance without formatting, example: 123456.78
    # <balance-formatted> - Account balance with formatting, example: 123,456.78
    # <balance-short> - Account balance with formatting, example: 123k
    balance: |-
        <green><account></green> <gray>(<account-type> account)</gray>
        <green>Balance:</green> <white><balance-formatted></white>
        <white><i>Owned by <account-owner></i></white>
        <i><gray><click:copy_to_clipboard:<account-id>><hover:show_text:'Click to copy account ID'><account-id></hover></click></gray></i>

    # List accounts
    list-accounts:
        header: "<green>Bank accounts</green>"
        # Same placeholders as balance
        entry: "<dark_gray>*</dark_gray> <gray><click:run_command:/bank balance <account-id>><hover:show_text:'<white><account></white><newline><gray><account-type> - <green><balance-formatted></green></gray><newline><gray>Click to view'><account></hover></click> - <white><balance-short></white></gray>"

    # Plugin reload
    reload: "<green>(!) Plugin configuration reloaded</green>"

    # Account created (same placeholders as balance)
    account-created: "<green>(!) Successfully created <account-type> account: <account></green> <click:run_command:/bank balance <account-id>><gray>Click to view</gray></click>"

    # Balance set (same placeholders as balance)
    balance-set: "<green>(!) Successfully set <white><account></white> <gray>(<account-type>, <account-id>)</gray> balance to <white><balance-formatted></white></green>"

    # Account name set (same placeholders as balance)
    name-set: "<green>(!) Successfully renamed account <white><account></white>"

    # Account deleted (same placeholders as balance)
    account-deleted: "<green>(!) Successfully deleted account <white><account></white>"

    # Transfer confirmation
    # Placeholders are the same as balance. Add prefix `from-` for account sending and `to-` for account receiving
    # Example: <to-account-id>, <from-balance-formatted>
    # Additional placeholders:
    # <amount> - Transfer amount without formatting, example: 123456.78
    # <amount-formatted> - Transfer amount with formatting, example: 123,456.78
    # <amount-short> - Transfer amount with formatting, example: 123k
    # <description> - Transfer description
    # <confirm-command> - Command to run to confirm transfer
    confirm-transfer: |-
        <green><bold>CONFIRM TRANSFER</bold></green>
        <green>From:</green> <white><from-account></white> <gray>(<from-account-type> account of <from-account-owner>, <from-account-id>)</gray>
        <green>To:</green> <white><to-account></white> <gray>(<to-account-type> account of <to-account-owner>, <to-account-id>)</gray>
        <green>Amount:</green> <white><amount-formatted></white>
        <green>Description:</green> <white><description></white>
        
        <click:run_command:<confirm-command>><hover:show_text:'<green>Click to confirm transfer</green>'><green>[I CONFIRM]</green></hover></click>

    # Transfer sent (same placeholders as confirm-transfer, except confirm-command)
    # Additional placeholders:
    # <transaction-id> - Transaction ID
    transfer-sent: <green>(!) Successfully sent <white><amount-formatted></white> from <hover:show_text:'<white><from-account></white><newline><gray><from-account-type> - <green><from-balance-formatted></green></gray><newline><gray>Owned by <from-account-owner></gray><newline><gray><from-account-id></gray>'><white><from-account></white></hover> to <hover:show_text:'<white><to-account></white><newline><gray><to-account-type></gray><newline><gray>Owned by <to-account-owner></gray><newline><gray><to-account-id></gray>'><white><to-account></white></hover></green> <click:copy_to_clipboard:<transaction-id>><hover:show_text:'Click to copy transaction ID'><gray>#<transaction-id></gray></hover></click>

    # Transfer received (same placeholders as transfer-sent)
    transfer-received: <green>(!) You have received <white><amount-formatted></white> from <hover:show_text:'<white><from-account></white><newline><gray><from-account-type></gray><newline><gray>Owned by <from-account-owner></gray><newline><gray><from-account-id></gray>'><white><from-account></white></hover> in your <hover:show_text:'<white><to-account></white><newline><gray><to-account-type> - <green><to-balance-formatted></green></gray><newline><gray>Owned by <to-account-owner></gray><newline><gray><to-account-id></gray>'><white><to-account></white></hover> account:</green> <white><description></white> <click:copy_to_clipboard:<transaction-id>><hover:show_text:'Click to copy transaction ID'><gray>(#<transaction-id>)</gray></hover></click>